# Generated by Django 3.1.3 on 2022-05-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApresentacaoPesquisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_texto', models.CharField(max_length=50)),
                ('segundo_texto', models.CharField(max_length=50)),
                ('terceiro_texto', models.TextField(max_length=400)),
                ('quarto_texto', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='SlidesPesquisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_texto', models.CharField(max_length=50)),
                ('segundo_texto', models.CharField(max_length=50)),
                ('terceiro_texto', models.TextField(max_length=400)),
                ('quarto_texto', models.TextField(max_length=400)),
                ('quinto_texto', models.TextField(max_length=400)),
            ],
        ),
    ]
