# Generated by Django 3.1.3 on 2022-05-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apresentacaopesquisa',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='imagem//%Y/%m/%d'),
        ),
    ]
