# Generated by Django 3.1.3 on 2022-05-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_apresentacaopesquisa_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidespesquisa',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='imagem_slide//%Y/%m/%d'),
        ),
    ]
