# Generated by Django 3.1.3 on 2022-06-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20220529_0228'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposViolencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(max_length=400)),
            ],
        ),
    ]
