# Generated by Django 3.1.3 on 2022-06-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_tiposviolencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('subtitulo', models.CharField(max_length=150)),
                ('texto_auxiliar', models.CharField(max_length=350)),
                ('ultimo_texto', models.CharField(max_length=150)),
            ],
        ),
    ]
