# Generated by Django 3.1.3 on 2022-06-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='texto_auxiliar',
            field=models.CharField(max_length=485),
        ),
    ]
