# Generated by Django 3.1.3 on 2022-06-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_sobremetodologia_sobrepesquisa_sobrepesquisadora'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apresentacaopesquisa',
            options={'verbose_name': 'Apresentação Pesquisa', 'verbose_name_plural': 'Apresentação Pesquisa'},
        ),
        migrations.AlterModelOptions(
            name='guiavideos',
            options={'verbose_name': 'Guia Videos', 'verbose_name_plural': 'Guia Videos'},
        ),
        migrations.AlterModelOptions(
            name='hero',
            options={'verbose_name': 'Hero', 'verbose_name_plural': 'Hero'},
        ),
        migrations.AlterModelOptions(
            name='linksexternos',
            options={'verbose_name': 'Links Externos', 'verbose_name_plural': 'Links Externos'},
        ),
        migrations.AlterModelOptions(
            name='slidespesquisa',
            options={'verbose_name': 'Slides Pesquisa', 'verbose_name_plural': 'Slides Pesquisa'},
        ),
        migrations.AlterModelOptions(
            name='sobremetodologia',
            options={'verbose_name': 'Sobre Metodologia', 'verbose_name_plural': 'Sobre Metodologia'},
        ),
        migrations.AlterModelOptions(
            name='sobrepesquisa',
            options={'verbose_name': 'Sobre Pesquisa', 'verbose_name_plural': 'Sobre Pesquisa'},
        ),
        migrations.AlterModelOptions(
            name='sobrepesquisadora',
            options={'verbose_name': 'Sobre Pesquisadora', 'verbose_name_plural': 'Sobre Pesquisadora'},
        ),
        migrations.AlterModelOptions(
            name='tiposviolencia',
            options={'verbose_name': 'Tipos Violência', 'verbose_name_plural': 'Tipos Violência'},
        ),
        migrations.AlterField(
            model_name='sobremetodologia',
            name='texto',
            field=models.TextField(max_length=550),
        ),
        migrations.AlterField(
            model_name='sobrepesquisa',
            name='texto',
            field=models.TextField(max_length=550),
        ),
        migrations.AlterField(
            model_name='sobrepesquisadora',
            name='texto',
            field=models.TextField(max_length=550),
        ),
    ]
