# Generated by Django 3.1 on 2022-06-09 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20220607_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apresentacaopesquisa',
            name='imagem',
        ),
    ]
