# Generated by Django 3.1 on 2022-06-09 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_remove_apresentacaopesquisa_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slidespesquisa',
            name='imagem',
        ),
    ]
