# Generated by Django 3.1.3 on 2022-06-11 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_remove_slidespesquisa_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slidespesquisa',
            name='quinto_texto',
        ),
    ]
