# Generated by Django 3.1.3 on 2022-06-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_remove_slidespesquisa_quinto_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposviolencia',
            name='slug',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
